ci: fix version consistency check

diff --git a/.forgejo/workflows/main.yaml b/.forgejo/workflows/main.yaml
--- a/.forgejo/workflows/main.yaml
+++ b/.forgejo/workflows/main.yaml
@@ -12,6 +12,7 @@ env:
   NODE_VERSION: '24.10.0'
   PNPM_VERSION: '10.30.3'
   RUST_VERSION: '1.92.0'
+  YQ_VERSION: v4.50.1
 
 jobs:
   check_license_headers:
@@ -172,30 +173,30 @@ jobs:
           name: linux-bundles
           path: ${{ forgejo.workspace }}/target/linux
 
-      - name: Setup version
-        id: setup_version
+      - name: Install yq
         run: |
-          export CARGO_PACKAGE_VERSION="$(cargo pkgid | cut -d# -f2)"
-          if [[ "$FORGEJO_REF" == refs/tags/* ]]; then
-            TAG_NAME="${FORGEJO_REF#refs/tags/}"
-            if [ "$CARGO_PACKAGE_VERSION" != "$TAG_NAME" ]; then
-              echo "Error: The version in Cargo.toml ($CARGO_PACKAGE_VERSION) does not match the release tag ($TAG_NAME)."
-              exit 1
-            fi
-            echo "revision=$TAG_NAME" >> $FORGEJO_OUTPUT
-          else
-            export SHORT_CARGO_VERSION="$(echo $CARGO_PACKAGE_VERSION | cut -d '-' -f1)"
-            export NEW_VERSION="$SHORT_CARGO_VERSION+$FORGEJO_SHA"
-            sed -i "s/^version = \"$CARGO_PACKAGE_VERSION\"/version = \"$NEW_VERSION\"/" "Cargo.toml"
-            echo "revision=$NEW_VERSION" >> $FORGEJO_OUTPUT
-          fi
+          case "$(uname -m)" in
+            x86_64|amd64)  ARCH="amd64" ;;
+            aarch64|arm64) ARCH="arm64" ;;
+            *) echo "Unsupported architecture." && exit 1 ;;
+          esac
+          mkdir -p "$HOME/.local/bin"
+          wget "https://github.com/mikefarah/yq/releases/download/${{ env.YQ_VERSION }}/yq_linux_${ARCH}" -O "$HOME/.local/bin/yq"
+          chmod +x "$HOME/.local/bin/yq"
+          echo "$HOME/.local/bin" >> "$FORGEJO_PATH"
 
-      - name: Print revision
-        run: echo "Revision is ${{ steps.setup_version.outputs.revision }}"
+      - name: Check version consistency
+        run: |
+          export CARGO_PACKAGE_VERSION="$(yq -oy '.package.version' Cargo.toml)"
+          TAG_NAME="${FORGEJO_REF#refs/tags/}"
+          if [ "$CARGO_PACKAGE_VERSION" != "$TAG_NAME" ]; then
+            echo "Error: The version in Cargo.toml ($CARGO_PACKAGE_VERSION) does not match the release tag ($TAG_NAME)."
+            exit 1
+          fi
 
       - name: Move build artifacts
         run: |
-          export VERSION="${{ steps.setup_version.outputs.revision }}"
+          export VERSION="${FORGEJO_REF#refs/tags/}"
           mkdir -p ${{ forgejo.workspace }}/dist
           cp ${{ forgejo.workspace }}/target/linux/appimage/*.AppImage ${{ forgejo.workspace }}/dist/unichat-$VERSION.AppImage
           cp ${{ forgejo.workspace }}/target/linux/deb/*.deb ${{ forgejo.workspace }}/dist/unichat-$VERSION.deb
